-- ═══════════════════════════════════════════════════════════════════
-- Unkov — Per-investor token system
-- Run in: Supabase Dashboard → SQL Editor → New query → Run
-- Requires: 001_users.sql already applied
-- ═══════════════════════════════════════════════════════════════════

-- ─── 1. investor_tokens table ────────────────────────────────────
-- One row per investor. Token is a cryptographically random string
-- generated by the create-investor-token API, never by the browser.
CREATE TABLE IF NOT EXISTS public.investor_tokens (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Who this token belongs to
  investor_name  text NOT NULL,
  investor_email text NOT NULL,
  firm           text,
  notes          text,                -- e.g. "Met at YC demo day"

  -- The token itself — stored as a bcrypt hash, like a password.
  -- The plaintext is only ever shown once (in the CLI output).
  -- Format of plaintext: UNK-<32 random chars>
  token_hash     text NOT NULL,

  -- Lifecycle
  created_at     timestamptz NOT NULL DEFAULT now(),
  expires_at     timestamptz NOT NULL,             -- set by create-investor-token
  revoked_at     timestamptz,                      -- null = active
  used_at        timestamptz,                      -- null = never used
  used_count     integer NOT NULL DEFAULT 0,
  max_uses       integer NOT NULL DEFAULT 10,      -- stops credential sharing

  -- Audit
  created_by     text NOT NULL DEFAULT 'mustafa@unkov.com',
  last_ip        text,                             -- updated on each valid use
  last_used_at   timestamptz                       -- updated on each valid use
);

-- ─── 2. Indexes ───────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS investor_tokens_email_idx
  ON public.investor_tokens (investor_email);

CREATE INDEX IF NOT EXISTS investor_tokens_active_idx
  ON public.investor_tokens (expires_at, revoked_at)
  WHERE revoked_at IS NULL;

-- ─── 3. Row-level security ────────────────────────────────────────
-- This table is only accessible server-side via the service_role key.
-- No authenticated browser user should ever be able to read token hashes.
ALTER TABLE public.investor_tokens ENABLE ROW LEVEL SECURITY;

-- Deny all browser access — only the Vercel API (service_role) can read/write
CREATE POLICY "No browser access to investor tokens"
  ON public.investor_tokens
  FOR ALL
  USING (false);

-- ─── 4. Revoke helper ─────────────────────────────────────────────
-- Immediately invalidate a token. Call from SQL editor or admin API.
--   SELECT revoke_investor_token('investor@vc.com');
--   SELECT revoke_investor_token('investor@vc.com', 'token-id-uuid');
CREATE OR REPLACE FUNCTION public.revoke_investor_token(
  p_email text,
  p_id    uuid DEFAULT NULL
)
RETURNS integer AS $$
DECLARE revoked_count integer;
BEGIN
  UPDATE public.investor_tokens
  SET revoked_at = now()
  WHERE investor_email = p_email
    AND (p_id IS NULL OR id = p_id)
    AND revoked_at IS NULL;

  GET DIAGNOSTICS revoked_count = ROW_COUNT;
  RETURN revoked_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ─── 5. Active token view ─────────────────────────────────────────
-- Quick overview of who has access right now. Safe to query as admin.
CREATE OR REPLACE VIEW public.active_investor_tokens AS
  SELECT
    id,
    investor_name,
    investor_email,
    firm,
    notes,
    created_at,
    expires_at,
    used_count,
    max_uses,
    last_used_at,
    last_ip,
    CASE
      WHEN revoked_at IS NOT NULL       THEN 'revoked'
      WHEN expires_at < now()           THEN 'expired'
      WHEN used_count >= max_uses       THEN 'exhausted'
      ELSE                                   'active'
    END AS status
  FROM public.investor_tokens
  ORDER BY created_at DESC;

-- ─── 6. Verify ────────────────────────────────────────────────────
-- After running, check:
-- SELECT investor_name, investor_email, status FROM public.active_investor_tokens;
